DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS employee;

CREATE TABLE department (
        id INTEGER AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR (30) NOT NULL
);

CREATE TABLE role (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL NOT NULL,
    department_id INTEGER NULL,
    CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES deaprtment(id) ON DELETE SET NULL
);

